// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQfhyPLLDxZv_bwOpRq1kSCCjB5xFlYfc',
    appId: '1:1027212583576:android:7769c1380f2b59eaa426ed',
    messagingSenderId: '1027212583576',
    projectId: 'assisted-living-iot',
    storageBucket: 'assisted-living-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHsy-FW_kyz6gAlwSsfU6BcmRQzvEhJRw',
    appId: '1:1027212583576:ios:0c91b56d41aef3efa426ed',
    messagingSenderId: '1027212583576',
    projectId: 'assisted-living-iot',
    storageBucket: 'assisted-living-iot.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHsy-FW_kyz6gAlwSsfU6BcmRQzvEhJRw',
    appId: '1:1027212583576:ios:0c91b56d41aef3efa426ed',
    messagingSenderId: '1027212583576',
    projectId: 'assisted-living-iot',
    storageBucket: 'assisted-living-iot.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqLcAkC2cyJIhgcwdqzlIf1sH1ENpMk6o',
    appId: '1:1027212583576:web:4bf18b59581fbc6da426ed',
    messagingSenderId: '1027212583576',
    projectId: 'assisted-living-iot',
    authDomain: 'assisted-living-iot.firebaseapp.com',
    storageBucket: 'assisted-living-iot.firebasestorage.app',
    measurementId: 'G-H26EKK5K99',
  );
}
